version: '0.0.2'
source: "https://github.com/tr7zw/ModComposeTemplate/tree/1.20"
replacements:
  name: "FirstPerson"
  id: "firstperson"
  version: "2.2.4"
  relocationpackage: "dev.tr7zw.firstperson"
  curseforgeid: "333287"
  modrinthid: "H5XMjpHi"
enabledFlags:
  - autopublish
  - publishFabric
  - publishForge
  - modrinth
  - curseforge
rootProject:
  template: "."
subProjects:
  FPFabric:
    template: "Fabric"
    replacements:
      dependencies: "
      modCompileOnly 'maven.modrinth:playeranimator:0.4.0-test1-fabric'\n
      modCompileOnly 'maven.modrinth:freecam:1.1.6-mc1.19'\n
      "
  FPForge:
    template: "Forge"
    replacements:
      dependencies: '
      modImplementation "maven.modrinth:playeranimator:0.4.0-test1-forge"
      '